### ISSUE TITLE
Upgrade to Elm 0.19

### ISSUE THREAD

**Issue by julianpistorius** [basti1302/elm-human-readable-filesize#4]
Hi. Just checking if you were planning to upgrade this to 0.19, or if you needed help.

**Comment by basti1302** [comment]
If you want to take a stab at it, it would be very appreciated! 👍

**Comment by julianpistorius** [comment]
I have made progress on this, but got stuck on the last step. Will keep going.

**Comment by julianpistorius** [comment]
Good news! @cartoloupe showed up at ResBaz Hacky Hour last night and we pair-triaged the remaining steps of the upgrade. In the process of making a PR.
