### ISSUE TITLE
Allow support for 1.1.0/elm-0.18 by fixing elm-round package version

### ISSUE THREAD

**Issue by sohaibiftikhar** [basti1302/elm-human-readable-filesize#6]
elm-round has been updated to elm-0.19 in `1.0.3`. We could still support elm-0.18 by changing the elm-package.json to `"myrho/elm-round": "1.0.2 <= v < 1.0.3"` and backporting to `1.1.0`. I can make a PR but I need a branch (checked out from `1.1.0`) for that.

**Comment by basti1302** [comment]
Not sure how that would work. Can already published modules be overwritten? I guess maybe not? So even when fixing it, can it be published as 1.1.0 again?

Also, why would you need me to create a branch. You can just fork this repository and create a branch for yourself.

If republishing this as 1.1.0 for Elm 0.18 with a changed elm-package.json is not possible, another option would be that you fork this repo and publish it under a different name for Elm 0.18.

**Comment by sohaibiftikhar** [comment]
I already did this on a [fork](https://github.com/sohaibiftikhar/elm-human-readable-filesize/tree/1.1.0). I only suggested this so that the older versions here remain useable. If you don't think this is important then this can be closed.

You are allowed to republish the same tag again if you force push but I don't think its recommended. What I would do instead would be to tag it `1.1.0hotfix` or something.

**Comment by basti1302** [comment]
Sorry, I didn't mean to say this is unimportant. If we can get this fixed for Elm 0.18 I'm all for it.

Unfortunately I have not been doing any Elm recently so I am bit rusty and I don't know the internals of the Elm package catalog and the publish process super well.

What we want is that an elm install with that package as a dependency works for Elm 0.18. I'll need to do a bit of research how to achieve that. Or can you provide concrete steps already? Then I'm happy to do it.

I was thinking in terms of the `elm publish` command, and my guess is that it is not possible to publish a version again that has already been published. In the end, IIRC the packages are backed up by code on GitHub but I think the Elm package catalog also keeps some meta data about packages. If we can get away with just force pushing the fix to the 1.1.0 git tag, that would be easy.

**Comment by basti1302** [comment]
I just tried this out myself and now I'm not sure if anything needs to be done at all. My steps

```
> mkdir tmp
> cd tmp
> npm i -S elm@elm0.18.0
[some irrelevant npm output]
+ elm@0.18.0-exp5
> node_modules/.bin/elm-package install basti1302/elm-human-readable-filesize

To install basti1302/elm-human-readable-filesize I would like to add the following
dependency to elm-package.json:

    "basti1302/elm-human-readable-filesize": "1.1.0 <= v < 2.0.0"

May I add that to elm-package.json for you? [Y/n] Y

Some new packages are needed. Here is the upgrade plan.

  Install:
    basti1302/elm-human-readable-filesize 1.1.0
    elm-lang/core 5.1.1
    elm-lang/html 2.0.0
    elm-lang/virtual-dom 2.0.4
    myrho/elm-round 1.0.3

Do you approve of this plan? [Y/n] Y
Starting downloads...

  ● elm-lang/html 2.0.0
  ● basti1302/elm-human-readable-filesize 1.1.0
  ● elm-lang/virtual-dom 2.0.4
  ● elm-lang/core 5.1.1
  ● myrho/elm-round 1.0.3

Packages configured successfully!
```

Not that `elm-package install` was smart enough to install `myrho/elm-round 1.0.3` (the last version of elm-round that supports Elm 0.18) instead of `myrho/elm-round 1.0.4` (which is the first version to support Elm 0.19).

I then added a simple `Main.elm` file:

```
module Main exposing (..)
import Filesize exposing (..)
import Html
main = Html.text <| format 1234
```

Then:

```
> node_modules/.bin/elm-make Main.elm

Success! Compiled 40 modules.
Successfully generated index.html
```

When `index.html` is served, it correctly renders `1.23 kB`, as expected.

Maybe we can go back a step and you tell me exactly what issues you have in Elm 0.18 with this package and what setup you are using?

**Comment by sohaibiftikhar** [comment]
Thanks for the detailed answer.

The issue (if we can call it that) is with the package manager then. I am currently using [elm-github-install](https://www.npmjs.com/package/elm-github-install) for that and it seems to always pick up the latest version within the constraints specified in `elm-package.json`.

I think we can safely close this for now.

**Comment by basti1302** [comment]
Ah, interesting. Yeah, that sounds like a bug in elm-github-install indeed.
